### ISSUE TITLE
Add README

### ISSUE THREAD

**Issue by snowleopard** [nickcowle/alga-fsharp#1]
Hey @nickcowle!

I'm going to look at your translation of Alga to F# soon. I've never used F# though. Could you put together a short README on how to use/play with this library, e.g. just a couple basic command lines to build and run?

**Comment by snowleopard** [comment]
P.S.: I can see `build.sh`, but it's a bash script -- is there a build script for Windows (I'm mostly using it)?

**Comment by nickcowle** [comment]
Hey @snowleopard ,

For windows, you should be able to build the project by either running `build.cmd` or by running `build.fsx` with F# Interactive (`fsi build.fsx`).

There's quite a lot more that I want to add before it's really worth having a look at, though, so if you can hold off until next week, I'll add some more content and a proper README to explain how to build, etc.

**Comment by snowleopard** [comment]
Thanks! Sure, no rush. I'll read some F# docs in the meanwhile :)

**Comment by nickcowle** [comment]
Great :) http://fsharpforfunandprofit.com/site-contents/ is a really good place to start!

**Comment by nickcowle** [comment]
Hey @snowleopard,

Apologies for the (rather large!) delay. I've now added a README.md to the library - let me know if there's anything else you'd like to see in it or if you're happy for this issue to be closed.

Thanks,
Nick

**Comment by snowleopard** [comment]
Many thanks @nickcowle! Great to see you back, and with a lot of progress with the library :)

The README looks fine, so I'm closing this issue.
