### ISSUE TITLE
Status update and potential move

### ISSUE THREAD

**Issue by snowleopard** [nickcowle/alga-fsharp#2]
Hey @nickcowle!

Do you intend to continue working on this? 

Gregor Beyerle is interested in trying to experiment with FSharp implementation of Alga: 

https://twitter.com/GBeyerle/status/971093746665353221

I thought he might look here first. 

Note: there are experimental implementations in Agda and Scala here: https://github.com/algebraic-graphs. Perhaps we could move this repository there as well to make it easier to discover?

**Comment by nickcowle** [comment]
Hey @snowleopard,

Apologies for the radio silence – I’ve only just managed to find the time to work on this. I didn’t think the library was really worth moving to https://github.com/algebraic-graphs before, but now I’ve done more work on it, I’d be happy for it to move.

Thanks,
Nick

**Comment by snowleopard** [comment]
Many thanks @nickcowle! I've invited you to join the `algebraic-graphs` organisation. I believe that once you are in, you will be able to transfer the repository. I suggest we call it `algebraic-graphs/fsharp` for consistency with other implementations.

**Comment by nickcowle** [comment]
Hey @snowleopard,

Thanks for the invite to `algebraic-graphs`! I've transferred the repo across, but seem to have lost perms to change the repo name in the process - would you be able to rename it to `fsharp` as you suggested?

**Comment by snowleopard** [comment]
Thanks @nickcowle! Done. I've also made you an Admin in this repository -- you should be able to do everything you like with it :) 

I think this issue can now be closed.

P.S.: I hope to play with your library next week, after Haskell eXchange :)
